services:
  app:
    build: .
    container_name: soccer_manager_api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/soccer_manager?sslmode=disable
      - PORT=8080
      - JWT_SECRET=secret
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: soccer_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: soccer_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: